
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SET_AUTH = "SET_AUTH";
export const RESET_AUTH = "RESET_AUTH";


export const PARTICIPANTS_REQUEST = "PARTICIPANTS_REQUEST";
export const PARTICIPANTS_ERROR = "PARTICIPANTS_ERROR";
export const PARTICIPANTS_SUCCESS = "PARTICIPANTS_SUCCESS";

export const MESSAGES_REQUEST = "MESSAGES_REQUEST";
export const MESSAGES_ERROR = "MESSAGES_ERROR";
export const MESSAGES_SUCCESS = "MESSAGES_SUCCESS";

export const MESSAGES_HISTORY_REQUEST = "MESSAGES_HISTORY_REQUEST";
export const MESSAGES_HISTORY_ERROR = "MESSAGES_HISTORY_ERROR";
export const MESSAGES_HISTORY_SUCCESS = "MESSAGES_HISTORY_SUCCESS";


export const BASE_URL = "https://hackathons.space/api/admin";
// TODO remove it
export const TMP_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6Im9yZyIsImlhdCI6MTUyNjcwNDkzOCwiZXhwIjoxNTMxODg4OTM4fQ.H51j1iadlF8GDSdeg8NxBSe5KEYzPa9r4XoRMWo1_o0";